# Text Preprocessing

## Create data set

In [51]:
import pandas as pd
# ลอง Data ข้อความสัก 1 อัน
data1 = ["When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"]
data1

['When life gives you lemons, make lemonade! 🙂',
 'She bought 2 lemons for $1 at Maven Market.',
 'A dozen lemons will make a gallon of lemonade. [AllRecipes]',
 'lemon, lemon, lemons, lemon, lemon, lemons',
 "He's running to the market to get a lemon — there's a great sale today.",
 'Does Maven Market carry Eureka lemons or Meyer lemons?',
 'An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]',
 'iced tea is my favorite']

In [52]:
# เราควรนำเข้า Dataframe เพื่อใช้ประมวลผล
pd.set_option('display.max_colwidth',None)
data1 = pd.DataFrame(data1, columns=['sentence'])
data1

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [53]:
#ข้อความ Test นำเข้า Dataframe เหมือนกัน
test1 = [
    "We're going to start this course with traditional NLP applications.",
    "Then we'll move on to modern NLP theory.",
    "Finally, we'll wrap things up with modern NLP applications."
]
data_test1 = pd.DataFrame(test1, columns =['Test'])
data_test1

                                                                  Test
0  We're going to start this course with traditional NLP applications.
1                             Then we'll move on to modern NLP theory.
2          Finally, we'll wrap things up with modern NLP applications.

In [54]:
#lowertext
data1['sentence_clean'] = data1['sentence'].str.lower()
data1

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade. [allrecipes]
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea. [wikipedia]"
7,iced tea is my favorite,iced tea is my favorite

In [58]:
# remove ข้อความใน [] ออกกรณีไม่ใช้มันในการประมวลผล
data1['sentence_clean'] = data1['sentence_clean'].str.replace(r'\[.*?\]','', regex=True)
data1

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade.
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea."
7,iced tea is my favorite,iced tea is my favorite

In [60]:
data1['sentence_clean'] = data1['sentence_clean'].str.replace(r'[^\w\s]', '', regex=True)
data1

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂",when life gives you lemons make lemonade
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for 1 at maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons
4,He's running to the market to get a lemon — there's a great sale today.,hes running to the market to get a lemon theres a great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",an arnold palmer is half lemonade half iced tea
7,iced tea is my favorite,iced tea is my favorite

In [62]:
def cleanbasic(dataframe):	
	output = dataframe.str.lower()
	output = output.str.replace(r'\[.*?\]','', regex=True)
	output = output.str.replace(r'[^\w\s]', '', regex=True)
	return output

In [65]:
data1['sentence_clean'] = cleanbasic(data1['sentence_clean'])

In [67]:
data1

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂",when life gives you lemons make lemonade
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for 1 at maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons
4,He's running to the market to get a lemon — there's a great sale today.,hes running to the market to get a lemon theres a great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",an arnold palmer is half lemonade half iced tea
7,iced tea is my favorite,iced tea is my favorite

In [87]:
data_test['Test'] = cleanbasic(data_test['Test'])
data_test

                                                                Test
0  were going to start this course with traditional nlp applications
1                             then well move on to modern nlp theory
2           finally well wrap things up with modern nlp applications

In [12]:
##ฟังก์ชั่นจัดการเครียร์ทุกสิ่งอย่างพร้อมเข้า Model

import re
import unicodedata
import emoji
from bs4 import BeautifulSoup
from pythainlp import word_tokenize


def cleanfor_transformer(getdataframe):
    output = getdataframe.str.strip()
    output = output.apply(lambda x: unicodedata.normalize("NFC", x))
    
    # Remove HTML tags
    output = output.apply(lambda x: BeautifulSoup(x, "html.parser").get_text())
    
    # Remove URLs
    output = output.str.replace(r'http\S+|www\S+', '', regex=True)
    
    # Remove emails
    output = output.str.replace(r'\S+@\S+', '', regex=True)
    
    # Remove non-text except Thai/English numbers
    output = output.str.replace(r'[^\w\sก-๙]', ' ', regex=True)
    
    # Reduce multiple spaces
    output = output.str.replace(r'\s+', ' ', regex=True)
    
    # Reduce repeated characters
    output = output.str.replace(r'(.)\1{2,}', r'\1\1', regex=True)
    
    # Remove emoji
    output = output.apply(lambda x: emoji.replace_emoji(x, ''))
    
    # ตัดคำด้วย attacut 
    output = output.apply(
    lambda x: " ".join(word_tokenize(x, engine="attacut"))
)
   
    return output

In [96]:
data_test['Test'] = clean_text(data_test['Test'])
data_test

                                                                Test
0    going     start     course     traditional   nlp   applications
1                            well   move       modern   nlp   theory
2   finally   well   wrap   things       modern   nlp   applications

In [93]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\nat44\py311_env\lib\site-packages (6.1.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd

test123 = pd.DataFrame({
    "Test": [
        "ผมชอบกินข้าวมันไก่และน้ำซุป 🍲 http://example.com",
        "This is an example sentence with stopwords and email test@example.com"
    ]
})

test123['Test'] = clean_text(test123['Test'])
print(test123)

                                                Test
0                      ผม ชอบ กิน ข้าว ไก่ น้ำ ซุป
1        example   sentence     stopwords     ema...

In [3]:
import pandas as pd
children_book = pd.read_csv(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\childrens_books.csv')
children_book

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young..."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,The Very Hungry Caterpillar tells the story of...
2,3,The Giving Tree,Shel Silverstein,1964,4.38,The Giving Tree is a touching and bittersweet ...
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convi..."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime s..."
...,...,...,...,...,...,...
95,96,Stone Soup,Jon J. Muth,2003,4.18,Stone Soup is a classic folktale retold by Jon...
96,97,A Light in the Attic,Shel Silverstein,1981,4.36,A Light in the Attic is a collection of quirky...
97,98,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,1999,4.58,Harry Potter and the Prisoner of Azkaban is th...
98,99,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,1998,4.43,Harry Potter and the Chamber of Secrets is the...
99,100,The Three Billy Goats Gruff,Paul Galdone,1973,4.17,The Three Billy Goats Gruff is a retelling of ...

In [5]:
!conda list

'conda' is not recognized as an internal or external command,
operable program or batch file.

In [ ]:
!pip list

## Text Preprocessing with Spacy

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm
import spacy
nlp = spacy.load('en_core_web_sm')

In [6]:
text_1 = 'im selling lemons for $5 today'
text_1

'im selling lemons for $5 today'

In [7]:
clean = nlp(text_1)
clean

im selling lemons for $5 today

In [9]:
[token.text for token in clean]

['i', 'm', 'selling', 'lemons', 'for', '$', '5', 'today']

In [10]:
[token.lemma_ for token in clean]

['I', 'm', 'sell', 'lemon', 'for', '$', '5', 'today']

In [6]:
text_2 = 'I am very happiness and Success to learn Data Science'
clean2 = nlp(text_2)

In [7]:
[token.lemma_ for token in clean2]

['I',
 'be',
 'very',
 'happiness',
 'and',
 'success',
 'to',
 'learn',
 'Data',
 'science']

In [14]:
[token.lemma_ for token in clean2 if not token.is_stop]

['happiness', 'success', 'learn', 'Data', 'science']

In [4]:
pos = [(token.text, token.pos_) for token in clean2]
pos

[('I', 'PRON'),
 ('am', 'AUX'),
 ('very', 'ADV'),
 ('happiness', 'NOUN'),
 ('and', 'CCONJ'),
 ('Success', 'NOUN'),
 ('to', 'PART'),
 ('learn', 'VERB'),
 ('Data', 'PROPN'),
 ('Science', 'NOUN')]

In [10]:
import spacy
import pandas as pd
nlp = spacy.load('en_core_web_sm')

data1 = ["When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"]

pd.set_option('display.max_colwidth',None)
data1 = pd.DataFrame(data1,columns = ['sentence'])
data1

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [23]:
def cleanbasic(dataframe):	
	output = dataframe.str.lower()
	output = output.str.replace(r'\[.*?\]','', regex=True)
	output = output.str.replace(r'[^\w\s]', '', regex=True)
	return output

In [24]:
spa1 = data1_clean.sentence[0]
doc = nlp(spa1)
doc

NameError: name 'data1_clean' is not defined

In [25]:
#tokenize
[token.text for token in doc]

NameError: name 'doc' is not defined

In [25]:
#Lemmatization
[token.lemma_ for token in doc]

['when', 'life', 'give', 'you', 'lemon', 'make', 'lemonade']

In [28]:
#Stopword
norm = [token.lemma_ for token in doc if not token.is_stop]
norm1 = ' '.join(norm)
norm1

'life give lemon lemonade'

In [4]:
def mix_spacytoken(text):
    doc = nlp(text)
    output = [token.lemma_ for token in doc if not token.is_stop]
    output = ' '.join(output)
    return output

In [2]:
import spacy
import pandas as pd
nlp = spacy.load('en_core_web_sm')

data1 = ["When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"]

pd.set_option('display.max_colwidth',None)
data1 = pd.DataFrame(data1,columns = ['sentence'])
data1

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [3]:
data1['sentence_clean'] = cleanfor_transformer(data1['sentence'])
data1

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂",life gives lemons make lemonade
1,She bought 2 lemons for $1 at Maven Market.,bought 2 lemons 1 Maven Market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],dozen lemons make gallon lemonade AllRecipes
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons
4,He's running to the market to get a lemon — there's a great sale today.,running market get lemon great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,Maven Market carry Eureka lemons Meyer lemons
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",Arnold Palmer half lemonade half iced tea Wikipedia
7,iced tea is my favorite,iced tea favorite

In [5]:
data1['setence_spacy'] = data1['sentence_clean'].apply(mix_spacytoken)
data1

,sentence,sentence_clean,setence_spacy
0,"When life gives you lemons, make lemonade! 🙂",life gives lemons make lemonade,life give lemon lemonade
1,She bought 2 lemons for $1 at Maven Market.,bought 2 lemons 1 Maven Market,buy 2 lemon 1 Maven Market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],dozen lemons make gallon lemonade AllRecipes,dozen lemon gallon lemonade AllRecipes
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons,lemon lemon lemon lemon lemon lemon
4,He's running to the market to get a lemon — there's a great sale today.,running market get lemon great sale today,run market lemon great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,Maven Market carry Eureka lemons Meyer lemons,Maven Market carry Eureka lemon Meyer lemon
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",Arnold Palmer half lemonade half iced tea Wikipedia,Arnold Palmer half lemonade half iced tea Wikipedia
7,iced tea is my favorite,iced tea favorite,ice tea favorite

In [6]:
import pandas as pd
text3 = ['หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี😆 https://www.benjamasss.com',
        'พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน 😀 อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน phatcharawat@or.th',
        'P_ong has a piercing, harsh voice and has no skills other than shouting loudly.','ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง','ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี','บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด']
pd.set_option('display.max_colwidth',None)
dataBen = pd.DataFrame(text3,columns = ['Testcolumn'])
dataBen

                                                                                                                                                                                             Testcolumn
0  หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี😆 https://www.benjamasss.com
1                                                 พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน 😀 อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน phatcharawat@or.th
2                                                                                                                       P_ong has a piercing, harsh voice and has no skills other than shouting loudly.
3                                                                                                                                          ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง
4                                                                                                                                                           ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี
5                                                                                                          บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด

In [7]:
##ฟังก์ชั่นจัดการเครียร์ทุกสิ่งอย่างพร้อมเข้า Model

import re
import unicodedata
import emoji
from bs4 import BeautifulSoup
from pythainlp import word_tokenize


def cleanfor_transformer(getdataframe):
    output = getdataframe.str.strip()
    output = output.apply(lambda x: unicodedata.normalize("NFC", x))
    
    # Remove HTML tags
    output = output.apply(lambda x: BeautifulSoup(x, "html.parser").get_text())
    
    # Remove URLs
    output = output.str.replace(r'http\S+|www\S+', '', regex=True)
    
    # Remove emails
    output = output.str.replace(r'\S+@\S+', '', regex=True)
    
    # Remove non-text except Thai/English numbers
    output = output.str.replace(r'[^\w\sก-๙]', ' ', regex=True)
    
    # Reduce multiple spaces
    output = output.str.replace(r'\s+', ' ', regex=True)
    
    # Reduce repeated characters
    output = output.str.replace(r'(.)\1{2,}', r'\1\1', regex=True)
    
    # Remove emoji
    output = output.apply(lambda x: emoji.replace_emoji(x, ''))
    
   
    return output

In [8]:
dataBen['clean_ByMyfunction'] = cleanfor_transformer(dataBen['Testcolumn'])
dataBen

,Testcolumn,clean_ByMyfunction
0,หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี😆 https://www.benjamasss.com,หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี
1,พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน 😀 อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน phatcharawat@or.th,พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน
2,"P_ong has a piercing, harsh voice and has no skills other than shouting loudly.",P_ong has a piercing harsh voice and has no skills other than shouting loudly
3,ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง,ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง
4,ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี,ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี
5,บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด,บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_id = "clapAI/mmBERT-small-multilingual-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(model_id)

sentiment = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)
print(sentiment("อาหารร้านนี้อร่อยมาก บริการดีสุดๆ"))

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

[{'label': 'positive', 'score': 0.9744069576263428}]

In [10]:
%%time
import pandas as pd
import logging

#hide all non-critical warnings
logging.basicConfig(level=logging.ERROR)

# ใช้ apply เพื่อวิเคราะห์ทีละแถว
dataBen['sentiment'] = dataBen['clean_ByMyfunction'].apply(lambda x: sentiment(x)[0]['label'])
dataBen['score'] = dataBen['clean_ByMyfunction'].apply(lambda x: sentiment(x)[0]['score'])

label_map = {
    "positive": "บวก",
    "neutral": "กลาง",
    "negative": "ลบ"
}

dataBen['sentiment_text'] = dataBen['sentiment'].map(label_map)
dataBen

CPU times: total: 8.98 s
Wall time: 3.05 s

,Testcolumn,clean_ByMyfunction,sentiment,score,sentiment_text
0,หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี😆 https://www.benjamasss.com,หญิงอ้วน กินจุ มี Skill ตรวจคำผิดกับขีดเส้นใต้ ตรวจ Format อักษร นิสัยลูกแม้ค้าขายผัก พูดจาปากไม่ดี ชอบแขวะคนอื่นไปทั่ว อิจฉาริษยา เป็น DNA ของที่ทำงานแห่งนี้แม่งต้องมี,positive,0.809295,บวก
1,พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน 😀 อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน phatcharawat@or.th,พัชรวัฒน์ตั้งใจทำงานเต็มที่ไม่ยอมหลับนอนทำงานเพื่อส่วนงาน อนาคตได้อยู่ยาวๆ จนอายุ 55 ปี ได้สิ่งที่คาดหวังในชีวิตเป็น ผอสอ แน่นอน,positive,0.981380,บวก
2,"P_ong has a piercing, harsh voice and has no skills other than shouting loudly.",P_ong has a piercing harsh voice and has no skills other than shouting loudly,negative,0.971846,ลบ
3,ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง,ร้านนี้อาหารรสชาติแย่ จืดไปหน่อย เสริฟช้ารอเกือบครึ่งชั่วโมง,negative,0.996574,ลบ
4,ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี,ตัดผมกับร้านนี้ตัดไม่เป็นทรง ช่างพูดจาไม่ดี,negative,0.996507,ลบ
5,บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด,บริษัทนี้วัฒนธรรมแย่ สอนพนักงานให้ด่ากันเอง แถมรับลูกแม่ค้าขายผักมาทำงานปากตลาดด่าว่าไม่หยุด,negative,0.998190,ลบ

In [1]:
%%time
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import pandas as pd
pd.set_option('display.max_colwidth',None)

#hide all non-critical warnings
import logging
logging.basicConfig(level=logging.ERROR)

import torch
torch.set_num_threads(1)


workshop1 = pd.read_excel(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\Popchip_Reviews_Sentiment.xlsx')

model_id = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(model_id)

sentiment = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer,device=-1,
    truncation=True,      # ตัดข้อความที่เกินออก
    padding="max_length", # เติม padding ให้ครบ
    use_fast = True,  # faster token                 
    max_length=512        # จำกัดความยาวสูงสุด
)

# device=0 ใช้ GPU ตัวแรก (ถ้ามี NVIDIA CUDA)
# device=-1 บังคับใช้ CPU พวก GPU onboard ทั้งหลายที่ไม่รองรับ+

workshop1 = workshop1.head(30)
with torch.no_grad():
    sentiment_score = workshop1['Text'].apply(sentiment)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

CPU times: total: 21.7 s
Wall time: 27.5 s

In [2]:
sentiment_score[0][0]['label']

'POSITIVE'

In [3]:
sentiment_score[0][0]['score']

0.9935213923454285

In [ ]:
workshop1['Label_HF'] = sentiment_score.apply(lambda x: x[0]['label'])
workshop1['Score_HF'] = sentiment_score.apply(lambda x: x[0]['score'])
workshop1['Score1'] = workshop1.apply(lambda row: row['Score_HF'] if row['Label_HF'] == 'POSITIVE' else (-row['Score_HF'] if row['Label_HF'] == 'NEGATIVE' else 0), axis=1)
workshop1.head(10)

In [8]:
%%time
from transformers import AutoTokenizer, AutoModelForSequenceClassification ,pipeline
import pandas as pd
pd.set_option('display.max_colwidth',None)

import logging
logging.basicConfig(level=logging.ERROR)

import torch
torch.set_num_threads(1)

workshop2 = pd.read_csv(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\movie_reviews_sentiment.csv')

model_id = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(model_id)

sentiment = pipeline('sentiment-analysis',model=model,tokenizer=tokenizer,device=-1,
                     truncation = True, # ตัดข้อความที่เกินออก
                     padding = 'max_length', # เติม padding ให้ครบ
                     use_fast = True,  # faster token                 
                      max_length=512        # จำกัดความยาวสูงสุด
                    )
workshop2['critics_consensus'] = workshop2['critics_consensus'].fillna("").astype(str)

with torch.no_grad() :
          sentiment_score = workshop2['critics_consensus'].apply(sentiment)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

CPU times: total: 1min 22s
Wall time: 1min 25s

In [6]:
sentiment_score[0][0]

{'label': 'NEGATIVE', 'score': 0.7781784534454346}

In [ ]:
workshop2['Label_HF'] = sentiment_score.apply(lambda x: x[0]['label'])
workshop2['Score_HF'] = sentiment_score.apply(lambda x: x[0]['score'])
workshop2['Score1'] = workshop2.apply(lambda row: row['Score_HF'] if row['Label_HF'] == 'POSITIVE' else (-row['Score_HF'] if row['Label_HF'] == 'NEGATIVE' else 0), axis=1)
workshop2.head(20)[workshop2.head(20)['Label_HF'] == 'NEGATIVE']

In [ ]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification,pipeline
import pandas as pd
pd.set_option('display.max_colwidth',None)
import logging
logging.basicConfig(level=logging.ERROR)

model = 'dslim/bert-base-NER'
ner_analyzer = pipeline('ner',model=model,device=-1,aggregation_strategy='SIMPLE')
text4 = "I orderd a Trent Alexander-Arnold at Applebee's in Springfield."
ner_analyzer(text4)

# TEXT SUMMARIZATION

In [3]:
%%time
from transformers import pipeline
import pandas as pd
pd.set_option('display.max_colwidth',None)

import logging
logging.basicConfig(level=logging.ERROR)

model = "facebook/bart-large-cnn"
##อีก model 'sshleifer/distilbart-cnn-12-6' และ 't5-small / t5-base'


summarizer = pipeline('summarization',model=model,device=-1)
text5 =   """The lemon tree produces a pointed oval yellow fruit. Botanically this is a hesperidium, 
             a modified berry with a tough, leathery rind. The rind is divided into an outer colored layer or zest, 
             which is aromatic with essential oils, and an inner layer of white spongy pith. 
             Inside are multiple carpels arranged as radial segments. The seeds develop inside the carpels. 
             The space inside each segment is a locule filled with juice vesicles.[2]
             Lemons contain many phytochemicals, including polyphenols, terpenes, 
             and tannins.[3] Their juice contains slightly more citric acid than lime juice (about 47 g/L), 
             nearly twice as much as grapefruit juice, and about five times as much as orange juice.[4]
          """

summary = summarizer("summarize: " + text5,
                     max_length=120,
                     min_length=20,
                     do_sample=False)

print(summary[0])

{'summary_text': 'The lemon tree produces a pointed oval yellow fruit. Lemons contain many phytochemicals, including polyphenols, terpenes, and tannins. Their juice contains slightly more citric acid than lime juice (about 47 g/L)'}
CPU times: total: 41 s
Wall time: 15.7 s

In [2]:
%%time
from transformers import pipeline
import pandas as pd
pd.set_option('display.max_colwidth',None)

import logging
logging.basicConfig(level=logging.ERROR)

model = "preechanon/mt5-base-thaisum-text-summarization"
##อีก model 'sshleifer/distilbart-cnn-12-6' และ 't5-small / t5-base'


summarizer = pipeline('summarization',model=model,device=-1)
text_6 = """ต้นมะนาวให้ผลสีเหลืองรูปไข่ปลายแหลม ในทางพฤกษศาสตร์ถือเป็นเฮสเพอริเดียม
            ซึ่งเป็นผลเบอร์รี่ที่เปลี่ยนแปลงไป มีเปลือกแข็งและเหนียว เปลือกแบ่งออกเป็นชั้นนอกที่มีสีหรือที่เรียกว่าผิวสี
            ซึ่งมีกลิ่นหอมจากน้ำมันหอมระเหย และชั้นในเป็นเนื้อสีขาวคล้ายฟองน้ำ
            ภายในมีคาร์เพลหลายอันเรียงตัวเป็นแฉกตามแนวรัศมี เมล็ดจะเจริญเติบโตอยู่ภายในคาร์เพล
            ช่องว่างภายในแต่ละแฉกเรียกว่าโลคูล ซึ่งเต็มไปด้วยถุงน้ำผลไม้[2]
            มะนาวมีสารเคมีจากพืชหลายชนิด ได้แก่ โพลีฟีนอล เทอร์พีน
            และแทนนิน[3] น้ำมะนาวมีกรดซิตริกมากกว่าน้ำมะนาวเขียวเล็กน้อย (ประมาณ 47 กรัม/ลิตร)
            เกือบสองเท่าของน้ำเกรปฟรุต และประมาณห้าเท่าของน้ำส้ม[4]
            """


summary = summarizer("summarize: " + text_6,
                     max_length=160,
                     min_length=20,
                     do_sample=True)

print(summary[0])

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

{'summary_text': 'ต้นมะนาวให้ผลสีเหลืองรูปไข่ปลายแหลม ในทางพฤกษศาสตร์ถือเป็นเฮสเพอริเดียม ซึ่งเป็นผลเบอร์รี่ที่เปลี่ยนแปลงไป มีเปลือกแข็งและเหนียว เปลือกแบ่งออกเป็นชั้นนอกที่มีสีหรือที่เรียกว่าผิวสี ซึ่งมีกลิ่นหอมจากน้ํามันหอมระเหย และชั้นในเป็นเนื้อสีขาวคล้ายฟองน้ํา'}
CPU times: total: 5min 1s
Wall time: 2min 9s

In [1]:
%%time
from transformers import pipeline,AutoTokenizer,AutoModelForSequenceClassification
import pandas as pd
pd.set_option('display.max_colwidth',None)

import logging
logging.basicConfig(level=logging.ERROR)

import torch
torch.set_num_threads(1)


model1 = "facebook/bart-large-cnn"
##อีก model 'sshleifer/distilbart-cnn-12-6' และ 't5-small / t5-base'


model2 = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(model2)
model = AutoModelForSequenceClassification.from_pretrained(model2)

sentiment = pipeline('sentiment-analysis',model=model2,tokenizer=tokenizer,device=-1,
                     truncation = True, padding = 'max_length',
                     use_fast = True,  # faster token                 
                      max_length=512        # จำกัดความยาวสูงสุด
                    )

summary = pipeline('summarization',model=model1,device=-1)				


Test = pd.read_excel(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\Popchip_Reviews_Sentiment.xlsx')
Test1 = Test.head(10)
summary(Test1.Text[0])[0]['summary_text']

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Your max_length is set to 142, but your input_length is only 39. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=19)

CPU times: total: 37.6 s
Wall time: 1min 31s

'Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip.  My healthy eating program is saved. I love Popchips! I love them!! I love popchips. I hate chips.'

In [6]:
Test1.Text[0]

'Popchips are the bomb!!  I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip.  My healthy eating program is saved.'

In [ ]:
Test1['new_summary'] = Test1['Text'].apply(lambda x: summary(x,min_length=20,max_length=50) [0]['summary_text'])
Test1

In [3]:
sentiment_score2 = Test1['new_summary'].apply(sentiment)
Test1['Label_HF2'] = sentiment_score2.apply(lambda x: x[0]['label'])
Test1['Score_HF2'] = sentiment_score2.apply(lambda x: x[0]['score'])

Test1['Sentiment_HF2'] = Test1.apply(lambda row: row['Score_HF2'] if row['Label_HF2'] == 'POSITIVE' else -row['Score_HF2'],axis=1)
Test1

C:\Users\Nat44\AppData\Local\Temp\ipykernel_10868\2162092194.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Test1['Label_HF2'] = sentiment_score2.apply(lambda x: x[0]['label'])
C:\Users\Nat44\AppData\Local\Temp\ipykernel_10868\2162092194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Test1['Score_HF2'] = sentiment_score2.apply(lambda x: x[0]['score'])
C:\Users\Nat44\AppData\Local\Temp\ipykernel_10868\2162092194.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Test1['Sentiment_HF2'] = Test1.apply(lambda row: row['Score_HF2'] if row['Label_HF2'] == 'POSITIVE' else -row['Score_HF2'],axis=1)

,Id,UserId,Rating,Priority,Title,Text,Sentiment_VADER,new_summary,Label_HF2,Score_HF2,Sentiment_HF2
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,0.9244,I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,POSITIVE,0.997653,0.997653
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more.",0.7269,"I like the puffed nature of this chip that makes it more unique in the chip market. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come",POSITIVE,0.999189,0.999189
2,23691,A30NYUHEDLWI0Y,5,High,Great Alternative to Potato Chips,"I just love these chips! I was always a big fan of potato chips, but haven't had one since I discovered popchips. They are great for dipping or all alone. I am constantly re-ordering them. One note however-if you are on a low salt diet these chips are probably not for you. They are high in sodium. We go through a case every two months. If you love them it pays to join the subscribe and save program through Amazon. You save money and stay supplied!",0.9790,"I was always a big fan of potato chips, but haven't had one since I discovered popchips. They are great for dipping or all alone. If you are on a low salt diet these chips are probably not for you.",NEGATIVE,0.992971,-0.992971
3,23692,A2NU55U9LKTB5J,3,Low,Not somthing I would crave,"These tasted like potatoe stix, that we got in grade school with our lunches usually on pizza day. They were the bomb then, not so much now. Won't buy again unless I get them for cheap or free.",0.8689,"These tasted like potatoe stix, that we got in grade school with our lunches usually on pizza day. Won't buy again unless I get them for cheap or free.",NEGATIVE,0.998546,-0.998546
4,23693,A225F7QFP5LIW2,5,High,healthy and delicious,"These chips are great! They look almost like a flattened rice cake, but taste so much better, more like a potato chip. The bbq flavor is delicious. They are very low in fat and full of flavor. It is easy to eat an entire bag of these!",0.9613,"These chips are great! They look almost like a flattened rice cake, but taste so much better, more like a potato chip. The bbq flavor is delicious. They are very low in fat and full of flavor.",POSITIVE,0.999322,0.999322
5,23694,AWB39CSUQXSB3,2,High,On the strong side,The flavors of these are a bit on the strong side. Wish I hadn't bought so many...I thought I would love them since parmesan and garlic are two of my favorite flavors. Oh well...,0.9360,I thought I would love them since parmesan and garlic are two of my favorite flavors. The flavors of these are a bit on the strong side.,POSITIVE,0.999803,0.999803
6,23695,A1BZEHZ038EUL2,5,High,Love these!,"I love this brand of chips. By far, I like the cheddar potato the best. Second in line is the sour cream, and third is the BBQ. I recently bought 12 bags of Cheddar on Amazon!<br />These are much better than those baked chips out on the market (in my opinion). Oh, and an FYI, these are way better than rice cakes-people keep comparing the two and I totally disagree).<br />The 0.8 oz bag is perfect single size (pretty generous actually).<br />Yummy!",0.9866,"I love this brand of chips. By far, I like the cheddar potato the best. The 0.8 oz bag is perfect single size.",POSITIVE,0.999624,0.999624
7,23696,A8E9ZAG5Y5RKH,5,Low,Like crack,"These things are like crack, I can't stop eating them!! Hence why I buy them in 12 packs :)",0.7889,"These things are like crack, I can't stop eating them!! Hence why I buy them in 12 packs :)",POSITIVE,0.996904,0.996904
8,23697,A3W0GMJ0FYSW3J,5,High,Awesome healthIER snack option!,"I first had Popchips last week at a local deli in Miami. I was so impressed with them that I came online to find them (not even remembering the brand name) and I'm so happy that my favorite online retailer Amazon offers them. I don't necessarily want $20 worth of chips (LOL) but on the other hand, I love them so much that I do need that many so I can have half at home, and half at work (in different flavors). And I'm sure this price is much cheaper than buying them one by one at the deli I go to.<br /><br />I am a serious chip lover but am always looking for healthier alternatives. I love that these chips are low in calorie/fat but taste 10X better than baked chips. There's something about a need for salt n crunch that baked chips don't solve for me. I've found most of them to be bland, flat, weird, cracker-like. As soon as you put one of these chips in your mouth you'll realize that they're not lightweights at all. I love the salt/vinegar and was very surprised that they don't lack flavor or taste less salty/vinegar(y) than their high calorie counterparts. The crunch of the chip reminds me of a ligther alternative to a kettle chip or the General Mills chips, Bugle. I am such a fan, and now that I've found these chips on Amazon, I don't plan to buy any other kind.",0.9951,"Popchips are low in calorie/fat but taste 10X better than baked chips. The crunch of the chip reminds me of a ligther alternative to a kettle chip or the General Mills chips, Bugle.",NEGATIVE,0.983232,-0.983232
9,23698,A2HYHT45PHNIIG,5,Low,Great Chip,"Our local TJ's used to carry these, but no more. There's a Costco 30 miles away, but that seems too far to travel for a bag of chips. I finally did the subscribe & save to get them on a more regular basis.<br /><br />I like these chips very much, they have good texture & flavor. They hold up to dip as well. I've tried the salt & vineger and the cheese flavors, but plain is still my favorite.",0.9455,"I like these chips very much, they have good texture & flavor. Our local TJ's used to carry these, but no more. There's a Costco 30 miles away, but that seems too far to travel for a bag of chips",NEGATIVE,0.982608,-0.982608

In [ ]:
Test1[['Text','Label_HF2','Sentiment_VADER','Score_HF2','Sentiment_HF2']]

In [4]:
%%time
from transformers import pipeline,AutoTokenizer,AutoModelForSequenceClassification
import pandas as pd
pd.set_option('display.max_colwidth',None)

import logging
logging.basicConfig(level=logging.ERROR)

import torch
torch.set_num_threads(1)


model1 = "facebook/bart-large-cnn"
##อีก model 'sshleifer/distilbart-cnn-12-6' และ 't5-small / t5-base'

summary = pipeline('summarization',model=model1,device=-1)


Test = pd.read_csv(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\childrens_books.csv')
Test1 = Test.head(15)
summary(Test1.Description[0])[0]['summary_text']

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Your max_length is set to 142, but your input_length is only 89. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=44)

CPU times: total: 16 s
Wall time: 17.6 s

"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."

In [7]:
Test1['new_summary'] = Test1['Description'].apply(lambda x: summary(x,min_length=20,max_length=70,early_stopping=True,length_penalty=.8) [0]['summary_text'])
Test1

C:\Users\Nat44\AppData\Local\Temp\ipykernel_9316\822544926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Test1['new_summary'] = Test1['Description'].apply(lambda x: summary(x,min_length=20,max_length=70,early_stopping=True,length_penalty=.8) [0]['summary_text'])

,Ranking,Title,Author,Year,Rating,Description,new_summary
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.","Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.","Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.","Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",Dr. Seuss’s classic story encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.","Goodnight Moon is a gentle, rhythmic bedtime story. The simple illustrations by Clement Hurd complement the soothing nature of the story."
5,6,Charlotte’s Web,E.B. White,1952,4.20,"Charlotte’s Web tells the story of a pig named Wilbur and his friendship with Charlotte, a clever spider who saves his life. Set on a farm, the novel explores themes of friendship, loyalty, and the cycle of life. Through Charlotte’s wise words and actions, Wilbur learns about love and sacrifice. White’s writing is filled with warmth and humor, and it’s a perfect read for both children and adults, dealing with timeless themes.","Charlotte’s Web tells the story of a pig named Wilbur and his friendship with Charlotte, a clever spider who saves his life. The novel explores themes of friendship, loyalty, and the cycle of life."
6,7,"The Cat in the Hat (Cat in the Hat, #1)",Dr. Seuss,1957,4.19,"The Cat in the Hat is a landmark children’s book that tells the story of two siblings who are bored and stuck inside on a rainy day. Their day takes a wild turn when the mischievous Cat in the Hat shows up and creates chaos in their home, along with his companions, Thing 1 and Thing 2. The story’s playful rhymes and whimsical illustrations make it a fun and engaging introduction to early reading for young children.",The Cat in the Hat is a landmark children's book that tells the story of two siblings. The story’s playful rhymes and whimsical illustrations make it a fun and engaging introduction to early reading for young children.
7,8,Where the Sidewalk Ends,Shel Silverstein,1974,4.34,"Where the Sidewalk Ends is a collection of poems by Shel Silverstein that blend wit, humor, and thoughtful reflections on life. With its playful rhymes and sometimes surreal themes, the book invites children to explore their imagination and the joy of language. The poems are often accompanied by Silverstein’s signature drawings, which add to the whimsical atmosphere. It’s a perfect book for children who enjoy quirky, imaginative poetry.","Shel Silverstein's Where the Sidewalk Ends is a collection of poems by Shel Silverstein. With its playful rhymes and sometimes surreal themes, the book invites children to explore their imagination."
8,9,If You Give a Mouse a Cookie,Laura Joffe Numeroff,1985,4.29,"In If You Give a Mouse a Cookie, a little mouse asks for a cookie, and from there, a series of increasingly funny and unlikely events follow. Each request leads to another, showing the mouse's insatiable appetite for things he doesn’t necessarily need. This circular story uses humor to teach children about cause and effect while entertaining them with its playful illustrations and charming narrative.","In If You Give a Mouse a Cookie, a little mouse asks for a cookie. From there, a series of increasingly funny and unlikely events follow. This circular story uses humor to teach children about cause and effect."
9,10,Love You Forever,Robert Munsch,1986,4.38,"Love You Forever tells the heartwarming story of a mother’s enduring love for her son as he grows from a baby to an adult. Despite the passage of time and changing circumstances, the mother’s love remains constant. This book explores themes of unconditional love and the bond between parent and child, making it a perfect book for sharing at bedtime or during moments of reflection.",Love You Forever tells the story of a mother's enduring love for her son. This book explores themes of unconditional love and the bond between parent and child.
10,11,Corduroy,Don Freeman,1968,4.33,"Corduroy tells the story of a stuffed bear named Corduroy, who lives in a department store and longs for a home. When a little girl named Lisa buys him, he finally finds the love and belonging he has always wanted. Through this sweet and simple story, Freeman explores themes of self-worth, acceptance, and friendship. The charming illustrations and lovable characters make it an endearing classic for young readers.","Corduroy tells the story of a stuffed bear named Corduroy, who lives in a department store and longs for a home. Through this sweet and simple story, Freeman explores themes of self-worth, acceptance, and friendship."
11,12,The Lorax,Dr. Seuss,1971,4.35,"The Lorax tells the story of the environmentalist creature known as the Lorax, who speaks for the trees in an effort to protect the environment from the destructive actions of the Once-ler. Dr. Seuss’s timely message about conservation, the importance of nature, and taking responsibility for the planet makes this book both entertaining and educational. The bold illustrations and rhyming text are classic Seuss, engaging young readers.","The Lorax tells the story of the environmentalist creature known as the Lorax. The bold illustrations and rhyming text are classic Seuss, engaging young readers."
12,13,Madeline,Ludwig Bemelmans,1939,4.26,"Madeline follows the adventures of a brave and spirited little girl living in a convent in Paris. When she falls ill, she shows resilience and courage, never losing her sense of adventure. Bemelmans' charming illustrations and engaging storytelling make Madeline a beloved character in children’s literature. Themes of independence, courage, and friendship make this a timeless classic.","Madeline follows the adventures of a brave and spirited little girl living in a convent in Paris. Themes of independence, courage, and friendship make this a timeless classic."
13,14,"Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",J.K. Rowling,1997,4.47,"Harry Potter and the Sorcerer’s Stone introduces readers to Harry Potter, an orphan who discovers that he is a wizard and attends the magical Hogwarts School of Witchcraft and Wizardry. Along with his new friends, Harry uncovers mysteries surrounding his past and the dark wizard who killed his parents. This book starts the beloved series and sets the stage for Harry’s journey, filled with magic, adventure, and friendship.","Harry Potter and the Sorcerer’s Stone introduces readers to Harry Potter, an orphan who discovers that he is a wizard. Along with his new friends, Harry uncovers mysteries surrounding his past and the dark wizard who killed his parents."
14,15,The Velveteen Rabbit,Margery Williams Bianco,1922,4.31,"The Velveteen Rabbit tells the story of a stuffed rabbit who longs to become real through the love of a child. As the rabbit experiences love and loss, he learns that true beauty comes from the heart. The book’s themes of love, transformation, and the passage of time make it a timeless classic that resonates with both children and adults. Its gentle message is beautifully complemented by the soft, nostalgic illustrations.","The Velveteen Rabbit is a timeless classic that resonates with both children and adults. Its gentle message is beautifully complemented by the soft, nostalgic illustrations."

In [ ]:
from transformers import pipeline

model ='gpt2'
generator = pipeline('text-generation',model=model,device=-1)

textsample = 'On a hot summer day,I love to drink cold lemonade because'

generator(textsample,max_length=50,num_return_sequences=1,do_sample=True)

In [2]:
from transformers import pipeline

model='sentence-transformers/all-MiniLM-L6-v2'
feature_extractor = pipeline('feature-extraction',model=model,device=-1)

text ='When life give you lemons,make lemonage! '

feature_extractor(text)[0][0][:5]

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Nat44\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

[-0.24495771527290344,
 0.13953319191932678,
 0.1451827585697174,
 0.03366134315729141,
 0.05766553431749344]

In [7]:
len(feature_extractor(text)[0][0])

384

In [ ]:
feature_extractor = pipeline('feature-extraction',model=model,device=-1)
text1 = 'When life give you lemons, make lemonade!'
feature_extractor(text1)[0][0]

In [2]:
from transformers import pipeline
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

model = 'sentence-transformers/all-MiniLM-L6-v2'
feature_extractor = pipeline('feature-extraction',model=model,device=-1)

movies = pd.read_csv(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\movie_reviews.csv')
embeddings = movies['movie_info'].apply(lambda x: np.mean(feature_extractor(x)[0], axis=0))
movie_embeddings = np.vstack(embeddings)
movie_embeddings[0][:10]

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

WARNING:tensorflow:From C:\Users\Nat44\py311_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

array([-0.19111351, -0.11548017, -0.04469398, -0.12137813, -0.17980681,
        0.18034078,  0.06348409, -0.05768498,  0.02180578, -0.15678119])

In [2]:
len(movie_embeddings)

166

In [3]:
movie_embeddings.shape

(166, 384)

In [4]:
len(movie_embeddings[0])

384

In [5]:
movies[movies['movie_title'] == 'Captain Marvel']

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus
25,Captain Marvel,PG-13,"Action & Adventure, Science Fiction & Fantasy",3/8/19,The story follows Carol Danvers as she becomes...,"Anna Boden, Ryan Fleck",female,78,53,"Packed with action, humor, and visual thrills,..."

In [5]:
movie_embeddings[25].shape

(384,)

In [6]:
Captain_Marvel_embeddings = movie_embeddings[25].reshape(1,-1)
Captain_Marvel_embeddings.shape

(1, 384)

In [7]:
movie_embeddings.shape

(166, 384)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarities = cosine_similarity(Captain_Marvel_embeddings, movie_embeddings)[0]
movies['similarity_to_Captain_Marvel'] = similarities
movies

In [3]:
def get_similarmovies(embeddings,movie_index,movie_details,top_n=3):
    # สร้าง Movie embedding สำหรับ movie index
    m_embedding = np.array(embeddings[movie_index]).reshape(1,-1)
    # คำนวน similarity score
    
    similarity_score = cosine_similarity(m_embedding, movie_embeddings)[0]
    similarity_score_series = pd.Series(similarity_score.flatten(),name='similarity_score')

    #bring in movie info
    movies_similarity_score_df = pd.concat([movie_details,similarity_score_series],axis=1)

    # นำมาใน movie info
    return movies_similarity_score_df.sort_values('similarity_score',ascending=False).iloc[0:top_n+1]

In [4]:
get_similarmovies(movie_embeddings,25,movies[['movie_title','movie_info','rating']],top_n=5)

,movie_title,movie_info,rating,similarity_score
25,Captain Marvel,The story follows Carol Danvers as she becomes...,PG-13,1.000000
131,The LEGO Movie 2: The Second Part,The much-anticipated sequel to the critically ...,PG,0.379317
31,Dark Phoenix,"In DARK PHOENIX, the X-MEN face their most for...",PG-13,0.364913
18,Avengers: Endgame,The grave course of events set in motion by Th...,PG-13,0.359192
45,Fast & Furious Presents: Hobbs & Shaw,Ever since hulking lawman Hobbs (Dwayne Johnso...,PG-13,0.326003
146,The Vanishing,Gerard Butler (Hunter Killer) and Peter Mullan...,R,0.316056

In [5]:
get_similarmovies(movie_embeddings,131,movies[['movie_title','movie_info','rating']],top_n=5)

,movie_title,movie_info,rating,similarity_score
131,The LEGO Movie 2: The Second Part,The much-anticipated sequel to the critically ...,PG,1.000000
36,Dumbo,"From Disney and visionary director Tim Burton,...",PG,0.395949
25,Captain Marvel,The story follows Carol Danvers as she becomes...,PG-13,0.379317
140,The Secret Life of Pets 2,THE SECRET LIFE OF PETS 2 will follow summer 2...,PG,0.377312
154,Triple Threat,"TRIPLE THREAT, the newest feature from Johnson...",R,0.375324
132,The Lion King,"From Disney Live Action, director Jon Favreau'...",PG,0.368818

In [8]:
import pandas as pd
import numpy as np
from transformers import pipeline
from sklearn.metrics.pairwise import cosine_similarity

model = 'sentence-transformers/all-MiniLM-L6-v2'
feature_extraction = pipeline('feature-extraction',model = model,device=-1)

book_df = pd.read_csv(r'D:\เรียน Data Science\NLP แบบดีหน่อย\Natural+Language+Processing+in+Python\Course Materials\Data\childrens_books.csv')

embeddings = book_df['Description'].apply(lambda x: np.mean(feature_extraction(x)[0], axis=0))
embeddings_book = np.vstack(embeddings)
embeddings_book.shape

C:\Users\Nat44\py311_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

(100, 384)

In [9]:
def get_similarbook(embeddings,book_index,description,top_n=3):

    # ระบุ สำหรับ book 
    m_embedding = np.array(embeddings[book_index]).reshape(1,-1)

    # คำนวน similarity score
    
    similarity_score = cosine_similarity(m_embedding, embeddings_book)[0]
    similarity_score_series = pd.Series(similarity_score.flatten(),name='similarity_score')

    # นำมาใน movie info
    book_similarity_score_df = pd.concat([description,similarity_score_series],axis=1)

    # Display movie recs
    return book_similarity_score_df.sort_values('similarity_score',ascending=False).iloc[0:top_n+1]

In [6]:
book_df

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young..."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,The Very Hungry Caterpillar tells the story of...
2,3,The Giving Tree,Shel Silverstein,1964,4.38,The Giving Tree is a touching and bittersweet ...
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convi..."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime s..."
...,...,...,...,...,...,...
95,96,Stone Soup,Jon J. Muth,2003,4.18,Stone Soup is a classic folktale retold by Jon...
96,97,A Light in the Attic,Shel Silverstein,1981,4.36,A Light in the Attic is a collection of quirky...
97,98,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,1999,4.58,Harry Potter and the Prisoner of Azkaban is th...
98,99,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,1998,4.43,Harry Potter and the Chamber of Secrets is the...
99,100,The Three Billy Goats Gruff,Paul Galdone,1973,4.17,The Three Billy Goats Gruff is a retelling of ...

In [10]:
get_similarbook(embeddings_book,10,book_df[['Title','Description','Rating']],top_n=5)

,Title,Description,Rating,similarity_score
10,Corduroy,Corduroy tells the story of a stuffed bear nam...,4.33,1.000000
36,"Pippi Longstocking (Pippi Långstrump, #1)",Pippi Longstocking tells the story of a free-s...,4.15,0.535732
14,The Velveteen Rabbit,The Velveteen Rabbit tells the story of a stuf...,4.31,0.521524
77,The Tale of Despereaux,The Tale of Despereaux tells the story of a sm...,4.07,0.488632
34,Horton Hears a Who!,Horton Hears a Who! tells the story of Horton ...,4.21,0.476597
93,Horton Hatches the Egg,"In Horton Hatches the Egg, the kind-hearted el...",4.19,0.470891