In [ ]:
import pandas as pd
data = [10,20,30,40,'SomO']
df = pd.DataFrame(data,columns = ['Age'])
df

In [ ]:
import pandas as pd
data1 = (10,20,30,40,'SomO')
cols = ['Age']
df1 = pd.DataFrame(data1,columns = cols)
df1

In [ ]:
import pandas as pd
data3 = [['คีย์บอร์ด','อุปกรณ์คอม',1200],['ตุ๊กตา','ของเล่น',1300],['Sumsung S20','มือถือ',40000]]
cols = ['สินค้า','ประเภท','ราคา']
df3 = pd.DataFrame(data3,columns = cols)
df3

In [ ]:
import pandas as pd

Product1 = ['คีย์บอร์ด','ตุ๊กตา','Sumsung S20']
Category1 = ['อุปกรณ์คอม','ของเล่น','มือถือ']
Price1 = [1200,1300,40000]

data4 =list(zip(Product1 ,Category1,Price1))

cols = ['สินค้า','ประเภท','ราคา']
df4 = pd.DataFrame(data4,columns = cols)
df4

In [20]:
import pandas as pd

data =[{ 'productname' :'sumsung s20','category' :'มือถือ', 'price' : 50000},{'productname' : 'ส้มโอ', 'category' : 'ผลไม้', 'price' : 150},{'productname': 'พี่ปู', 'category' : 'อาหารทะเล', 'price' : 300}]

df1 = pd.DataFrame(data)
df1

   productname   category  price
0  sumsung s20     มือถือ  50000
1        ส้มโอ      ผลไม้    150
2        พี่ปู  อาหารทะเล    300

In [1]:
import pandas as pd

data = {'productname' : ['Samsung S20','ตุ๊กตา','ส้มโอ','พี่ปู'], 'category' : ['มือถือ','ของเล่น','ผลไม้','อาหารทะเล'], 'price' : [50000,200,100,300]}

df1 = pd.DataFrame(data)
df1 = df1.set_index(['productname'])
df1

              category  price
productname
Samsung S20     มือถือ  50000
ตุ๊กตา         ของเล่น    200
ส้มโอ            ผลไม้    100
พี่ปู        อาหารทะเล    300

In [22]:
df1.to_csv(r'D:\text.csv',encoding = 'utf-8-sig',index = True,header = True)

In [ ]:
df1.to_excel(r'D:\test.xlsx')

In [ ]:
pip install pyarrow

In [ ]:
df1.to_parquet(r'D:\test.parquet')

In [24]:
df1 = pd.read_parquet(r'D:\test.parquet')

In [25]:
df1

              category  price
productname
Samsung S20     มือถือ  50000
ตุ๊กตา         ของเล่น    200
ส้มโอ            ผลไม้    100
พี่ปู        อาหารทะเล    300

In [27]:
cols = ['productname','category']
df1 = pd.read_excel(r'D:\test.xlsx', usecols = cols)

In [28]:
df1

   productname   category
0  Samsung S20     มือถือ
1       ตุ๊กตา    ของเล่น
2        ส้มโอ      ผลไม้
3        พี่ปู  อาหารทะเล

In [3]:
import pandas as pd
df1 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name = 'Sales Data')
df1

           Transaction Date  Product ID  Quantity Sold  Sale Price
0   2023-10-28 09:45:09.488          50              4       11.87
1   2023-10-28 09:45:09.488          35              1      358.02
2   2023-10-28 09:45:09.488          42              6      207.76
3   2023-10-28 09:45:09.488          19              5       17.01
4   2023-10-28 09:45:09.488          46              3      204.31
..                      ...         ...            ...         ...
995 2024-04-24 09:45:09.488          38              9      405.41
996 2024-04-24 09:45:09.488          19              9      454.87
997 2024-04-24 09:45:09.488          48              5      227.26
998 2024-04-24 09:45:09.488          31              7       59.93
999 2024-04-24 09:45:09.488           3              4      366.26

[1000 rows x 4 columns]

In [26]:
df1.to_numpy(dtype =object)

array([[Timestamp('2023-10-28 09:45:09.488000'), 50, 4, 11.87],
       [Timestamp('2023-10-28 09:45:09.488000'), 35, 1, 358.02],
       [Timestamp('2023-10-28 09:45:09.488000'), 42, 6, 207.76],
       ...,
       [Timestamp('2024-04-24 09:45:09.488000'), 48, 5, 227.26],
       [Timestamp('2024-04-24 09:45:09.488000'), 31, 7, 59.93],
       [Timestamp('2024-04-24 09:45:09.488000'), 3, 4, 366.26]],
      dtype=object)

In [4]:
df1['Sale Price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Sale Price
Non-Null Count  Dtype
--------------  -----
1000 non-null   float64
dtypes: float64(1)
memory usage: 7.9 KB

In [5]:
df1.mean(numeric_only = True)

Product ID        25.94300
Quantity Sold      5.51300
Sale Price       254.20032
dtype: float64

In [6]:
df1['Sale Price'][1]/df1['Sale Price'].mean()*100

140.84167950693373

In [7]:
df1['Transaction Date'].astype('datetime64[ns]')

0     2023-10-28 09:45:09.488
1     2023-10-28 09:45:09.488
2     2023-10-28 09:45:09.488
3     2023-10-28 09:45:09.488
4     2023-10-28 09:45:09.488
                ...
995   2024-04-24 09:45:09.488
996   2024-04-24 09:45:09.488
997   2024-04-24 09:45:09.488
998   2024-04-24 09:45:09.488
999   2024-04-24 09:45:09.488
Name: Transaction Date, Length: 1000, dtype: datetime64[ns]

In [8]:
df1['Sale Price'].astype('Float64')

0       11.87
1      358.02
2      207.76
3       17.01
4      204.31
        ...
995    405.41
996    454.87
997    227.26
998     59.93
999    366.26
Name: Sale Price, Length: 1000, dtype: Float64

In [9]:
df1[['Transaction Date','Sale Price']][1:9]

         Transaction Date  Sale Price
1 2023-10-28 09:45:09.488      358.02
2 2023-10-28 09:45:09.488      207.76
3 2023-10-28 09:45:09.488       17.01
4 2023-10-28 09:45:09.488      204.31
5 2023-10-28 09:45:09.488      359.88
6 2023-10-28 09:45:09.488      388.84
7 2023-10-29 09:45:09.488       36.77
8 2023-10-29 09:45:09.488      109.29

In [74]:
df1[['Transaction Date','Sale Price']][5:]

           Transaction Date  Sale Price
5   2023-10-28 09:45:09.488      359.88
6   2023-10-28 09:45:09.488      388.84
7   2023-10-29 09:45:09.488       36.77
8   2023-10-29 09:45:09.488      109.29
9   2023-10-29 09:45:09.488      334.89
..                      ...         ...
995 2024-04-24 09:45:09.488      405.41
996 2024-04-24 09:45:09.488      454.87
997 2024-04-24 09:45:09.488      227.26
998 2024-04-24 09:45:09.488       59.93
999 2024-04-24 09:45:09.488      366.26

[995 rows x 2 columns]

In [10]:
df1[1:3][['Transaction Date','Sale Price']]

         Transaction Date  Sale Price
1 2023-10-28 09:45:09.488      358.02
2 2023-10-28 09:45:09.488      207.76

In [11]:
df1.loc[1:3][['Transaction Date','Sale Price']]

         Transaction Date  Sale Price
1 2023-10-28 09:45:09.488      358.02
2 2023-10-28 09:45:09.488      207.76
3 2023-10-28 09:45:09.488       17.01

In [ ]:
df2 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name ='Customer Profile')
df2

In [17]:
df2['Name'] = df2['Name'].astype('string')
df2['Gender'] = df2['Gender'].astype('string')
df2['Age'] = df2['Age'].astype('Int64')
df2['Occupation'] = df2['Occupation'].astype('string')

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1000 non-null   string
 1   Gender      1000 non-null   string
 2   Age         1000 non-null   Int64
 3   Occupation  1000 non-null   string
dtypes: Int64(1), string(3)
memory usage: 32.4 KB

In [ ]:
df2[df2['Name'].str.contains('David')]

In [ ]:
for idx, row in df1.iterrows():
    print('Product ID ที่ {} มียอดขาย {}'.format(row['Product ID'],row['Sale Price']))

In [ ]:
df1[df1['Quantity Sold']<=2]

In [ ]:
df1[(df1['Transaction Date'] >= '2024-04-20') & (df1['Transaction Date'] <  '2024-04-21')]

In [ ]:
df1[(df1['Quantity Sold']<=2) & (df1['Sale Price'] > 470)]

In [138]:
df1[(df1['Quantity Sold']<=2) | (df1['Sale Price'] > 470)]

           Transaction Date  Product ID  Quantity Sold  Sale Price
1   2023-10-28 09:45:09.488          35              1      358.02
18  2023-10-30 09:45:09.488          44              2      346.64
19  2023-10-30 09:45:09.488          39              2      108.14
20  2023-10-30 09:45:09.488          50              9      495.75
27  2023-11-01 09:45:09.488          34              9      490.56
..                      ...         ...            ...         ...
970 2024-04-20 09:45:09.488          24              2       47.05
980 2024-04-22 09:45:09.488          33             10      488.88
989 2024-04-23 09:45:09.488          33              1      459.86
991 2024-04-24 09:45:09.488          18              2      339.51
993 2024-04-24 09:45:09.488          17              2      253.79

[252 rows x 4 columns]

In [7]:
df1[df1['Quantity Sold'].isin([2,4,6])]

           Transaction Date  Product ID  Quantity Sold  Sale Price
0   2023-10-28 09:45:09.488          50              4       11.87
2   2023-10-28 09:45:09.488          42              6      207.76
6   2023-10-28 09:45:09.488           7              4      388.84
9   2023-10-29 09:45:09.488          32              6      334.89
18  2023-10-30 09:45:09.488          44              2      346.64
..                      ...         ...            ...         ...
986 2024-04-23 09:45:09.488          26              4      376.92
987 2024-04-23 09:45:09.488          39              6      447.02
991 2024-04-24 09:45:09.488          18              2      339.51
993 2024-04-24 09:45:09.488          17              2      253.79
999 2024-04-24 09:45:09.488           3              4      366.26

[311 rows x 4 columns]

In [15]:
df2.sort_values(['Age', 'Occupation'],ascending=[True, False])

                    Gender  Age              Occupation
Name
Kayla West            Male   18            Video editor
Mark Stone      Non-binary   18           Social worker
Gina Mcclain        Female   18          Retail manager
Natalie Tucker        Male   18  Recruitment consultant
Diana Liu             Male   18       Quantity surveyor
...                    ...  ...                     ...
Courtney Baker      Female   70         Careers adviser
Amanda Turner   Non-binary   70                 Barista
Hunter Grant    Non-binary   70         Arboriculturist
Jill Brown      Non-binary   70     Animal technologist
Calvin Holder         Male   70   Aeronautical engineer

[1000 rows x 3 columns]

In [26]:
df1['Target_sold'] = df1['Quantity Sold'] * 1.5

In [29]:
df1

           Transaction Date  Product ID  Quantity Sold  Sale Price
0   2023-10-28 09:45:09.488          50              4       11.87
1   2023-10-28 09:45:09.488          35              1      358.02
2   2023-10-28 09:45:09.488          42              6      207.76
3   2023-10-28 09:45:09.488          19              5       17.01
4   2023-10-28 09:45:09.488          46              3      204.31
..                      ...         ...            ...         ...
995 2024-04-24 09:45:09.488          38              9      405.41
996 2024-04-24 09:45:09.488          19              9      454.87
997 2024-04-24 09:45:09.488          48              5      227.26
998 2024-04-24 09:45:09.488          31              7       59.93
999 2024-04-24 09:45:09.488           3              4      366.26

[1000 rows x 4 columns]

In [36]:
df1['Target_Quantity'] = df1['Quantity Sold'] * 1.5
df1['Target_Sales'] = df1['Target_Quantity'] * df1['Sale Price']
df1['Total_Cost'] = df1['Target_Sales'] *0.65
df1

,Transaction Date,Product ID,Quantity Sold,Sale Price,Target_Quantity,Target_Sales,Total_Cost
0,2023-10-28 09:45:09.488,50,4,11.87,6.0,71.220,46.29300
1,2023-10-28 09:45:09.488,35,1,358.02,1.5,537.030,349.06950
2,2023-10-28 09:45:09.488,42,6,207.76,9.0,1869.840,1215.39600
3,2023-10-28 09:45:09.488,19,5,17.01,7.5,127.575,82.92375
4,2023-10-28 09:45:09.488,46,3,204.31,4.5,919.395,597.60675
...,...,...,...,...,...,...,...
995,2024-04-24 09:45:09.488,38,9,405.41,13.5,5473.035,3557.47275
996,2024-04-24 09:45:09.488,19,9,454.87,13.5,6140.745,3991.48425
997,2024-04-24 09:45:09.488,48,5,227.26,7.5,1704.450,1107.89250
998,2024-04-24 09:45:09.488,31,7,59.93,10.5,629.265,409.02225
999,2024-04-24 09:45:09.488,3,4,366.26,6.0,2197.560,1428.41400

In [37]:
df1 = df1.rename(columns = {'Transaction Date' : 'Transaction_Datetime'})

In [38]:
df1

,Transaction_Datetime,Product ID,Quantity Sold,Sale Price,Target_Quantity,Target_Sales,Total_Cost
0,2023-10-28 09:45:09.488,50,4,11.87,6.0,71.220,46.29300
1,2023-10-28 09:45:09.488,35,1,358.02,1.5,537.030,349.06950
2,2023-10-28 09:45:09.488,42,6,207.76,9.0,1869.840,1215.39600
3,2023-10-28 09:45:09.488,19,5,17.01,7.5,127.575,82.92375
4,2023-10-28 09:45:09.488,46,3,204.31,4.5,919.395,597.60675
...,...,...,...,...,...,...,...
995,2024-04-24 09:45:09.488,38,9,405.41,13.5,5473.035,3557.47275
996,2024-04-24 09:45:09.488,19,9,454.87,13.5,6140.745,3991.48425
997,2024-04-24 09:45:09.488,48,5,227.26,7.5,1704.450,1107.89250
998,2024-04-24 09:45:09.488,31,7,59.93,10.5,629.265,409.02225
999,2024-04-24 09:45:09.488,3,4,366.26,6.0,2197.560,1428.41400

In [40]:
df55 = df1.drop(['Total_Cost','Target_Quantity'],axis=1 )

In [41]:
df55

,Transaction_Datetime,Product ID,Quantity Sold,Sale Price,Target_Sales
0,2023-10-28 09:45:09.488,50,4,11.87,71.220
1,2023-10-28 09:45:09.488,35,1,358.02,537.030
2,2023-10-28 09:45:09.488,42,6,207.76,1869.840
3,2023-10-28 09:45:09.488,19,5,17.01,127.575
4,2023-10-28 09:45:09.488,46,3,204.31,919.395
...,...,...,...,...,...
995,2024-04-24 09:45:09.488,38,9,405.41,5473.035
996,2024-04-24 09:45:09.488,19,9,454.87,6140.745
997,2024-04-24 09:45:09.488,48,5,227.26,1704.450
998,2024-04-24 09:45:09.488,31,7,59.93,629.265
999,2024-04-24 09:45:09.488,3,4,366.26,2197.560

In [44]:
df66 = df1.drop(df1[df1['Quantity Sold'] < 8].index)

In [47]:
df66

,Transaction_Datetime,Product ID,Quantity Sold,Sale Price,Target_Quantity,Target_Sales,Total_Cost
10,2023-10-29 09:45:09.488,29,9,329.59,13.5,4449.465,2892.15225
11,2023-10-29 09:45:09.488,43,10,12.14,15.0,182.100,118.36500
13,2023-10-29 09:45:09.488,26,8,264.88,12.0,3178.560,2066.06400
14,2023-10-30 09:45:09.488,33,10,396.60,15.0,5949.000,3866.85000
15,2023-10-30 09:45:09.488,23,9,122.05,13.5,1647.675,1070.98875
...,...,...,...,...,...,...,...
985,2024-04-22 09:45:09.488,28,10,15.74,15.0,236.100,153.46500
992,2024-04-24 09:45:09.488,31,9,305.71,13.5,4127.085,2682.60525
994,2024-04-24 09:45:09.488,21,10,432.69,15.0,6490.350,4218.72750
995,2024-04-24 09:45:09.488,38,9,405.41,13.5,5473.035,3557.47275
996,2024-04-24 09:45:09.488,19,9,454.87,13.5,6140.745,3991.48425

In [48]:
df77 = df1[df1['Quantity Sold'] >= 8]
df77

,Transaction_Datetime,Product ID,Quantity Sold,Sale Price,Target_Quantity,Target_Sales,Total_Cost
10,2023-10-29 09:45:09.488,29,9,329.59,13.5,4449.465,2892.15225
11,2023-10-29 09:45:09.488,43,10,12.14,15.0,182.100,118.36500
13,2023-10-29 09:45:09.488,26,8,264.88,12.0,3178.560,2066.06400
14,2023-10-30 09:45:09.488,33,10,396.60,15.0,5949.000,3866.85000
15,2023-10-30 09:45:09.488,23,9,122.05,13.5,1647.675,1070.98875
...,...,...,...,...,...,...,...
985,2024-04-22 09:45:09.488,28,10,15.74,15.0,236.100,153.46500
992,2024-04-24 09:45:09.488,31,9,305.71,13.5,4127.085,2682.60525
994,2024-04-24 09:45:09.488,21,10,432.69,15.0,6490.350,4218.72750
995,2024-04-24 09:45:09.488,38,9,405.41,13.5,5473.035,3557.47275
996,2024-04-24 09:45:09.488,19,9,454.87,13.5,6140.745,3991.48425

In [20]:
df2

                        Name      Gender  Age             Occupation
0             Breanna Bryant        Male   56   Broadcast journalist
1               James Barnes      Female   69  Nutritional therapist
2    Dr. Christine Maldonado      Female   46           Geoscientist
3              Donald Cooper      Female   32     Purchasing manager
4         Benjamin Singleton        Male   60        Energy engineer
..                       ...         ...  ...                    ...
995             Daniel Barry        Male   25               Musician
996           James Humphrey  Non-binary   66             Astronomer
997          William Barajas  Non-binary   52    Hospital pharmacist
998              Teresa Diaz        Male   69     Physicist, medical
999             Susan Harris      Female   32   Electronics engineer

[1000 rows x 4 columns]

In [26]:
import pandas as pd
newdata = [['Steven Gerrard','Male',42,'Manager Football']]
cols1 = ['Name','Gender','Age','Occupation']
df3 = pd.DataFrame(data=newdata,columns=cols1)
df3

             Name Gender  Age        Occupation
0  Steven Gerrard   Male   42  Manager Football

In [28]:
df4 = pd.concat([df2,df3],ignore_index=True)
df4

                         Name      Gender  Age             Occupation
0              Breanna Bryant        Male   56   Broadcast journalist
1                James Barnes      Female   69  Nutritional therapist
2     Dr. Christine Maldonado      Female   46           Geoscientist
3               Donald Cooper      Female   32     Purchasing manager
4          Benjamin Singleton        Male   60        Energy engineer
...                       ...         ...  ...                    ...
996            James Humphrey  Non-binary   66             Astronomer
997           William Barajas  Non-binary   52    Hospital pharmacist
998               Teresa Diaz        Male   69     Physicist, medical
999              Susan Harris      Female   32   Electronics engineer
1000           Steven Gerrard        Male   42       Manager Football

[1001 rows x 4 columns]

In [31]:
df1

           Transaction Date  Product ID  Quantity Sold  Sale Price
0   2023-10-28 09:45:09.488          50              4       11.87
1   2023-10-28 09:45:09.488          35              1      358.02
2   2023-10-28 09:45:09.488          42              6      207.76
3   2023-10-28 09:45:09.488          19              5       17.01
4   2023-10-28 09:45:09.488          46              3      204.31
..                      ...         ...            ...         ...
995 2024-04-24 09:45:09.488          38              9      405.41
996 2024-04-24 09:45:09.488          19              9      454.87
997 2024-04-24 09:45:09.488          48              5      227.26
998 2024-04-24 09:45:09.488          31              7       59.93
999 2024-04-24 09:45:09.488           3              4      366.26

[1000 rows x 4 columns]

In [36]:
df1['totalsale'] = df1['Quantity Sold']*df1['Sale Price']
df1.sum(axis=0,numeric_only=True)

Product ID         25943.00
Quantity Sold       5513.00
Sale Price        254200.32
totalsale        1417123.88
dtype: float64

In [42]:
df1.notnull().sum()

Transaction Date    1000
Product ID          1000
Quantity Sold       1000
Sale Price          1000
totalsale           1000
dtype: int64

In [44]:
df1.describe()

,Transaction Date,Product ID,Quantity Sold,Sale Price,totalsale
count,1000,1000.000000,1000.000000,1000.00000,1000.00000
mean,2024-01-25 02:34:35.888000512,25.943000,5.513000,254.20032,1417.12388
min,2023-10-28 09:45:09.488000,1.000000,1.000000,10.01000,13.76000
25%,2023-12-11 09:45:09.488000,14.000000,3.000000,140.80750,444.61500
50%,2024-01-22 09:45:09.488000,26.000000,5.000000,253.27500,1112.07000
75%,2024-03-09 09:45:09.488000,38.000000,8.000000,374.04750,2092.83750
max,2024-04-24 09:45:09.488000,50.000000,10.000000,498.93000,4964.80000
std,NaN,14.107898,2.829813,141.79436,1157.54787

In [3]:
import pandas as pd
df5 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name = 'Sales Data Missing')
df5.head(10)
dataadd = [[pd.Timestamp('2023-10-29 09:45:09.488'),32,6,334.89],[pd.Timestamp('2023-10-29 09:45:09.488'),13,3,109.29]]
cols = ['Transaction Date','Product ID','Quantity Sold','Sale Price']
df6 = pd.DataFrame(data=dataadd,columns=cols)
df5 = pd.concat([df5,df6],ignore_index=True)
df5

            Transaction Date  Product ID  Quantity Sold  Sale Price
0    2023-10-28 09:45:09.488          50              4       11.87
1    2023-10-28 09:45:09.488          35              1      358.02
2    2023-10-28 09:45:09.488          42              6         NaN
3    2023-10-28 09:45:09.488          19              5       17.01
4    2023-10-28 09:45:09.488          46              3      204.31
...                      ...         ...            ...         ...
997  2024-04-24 09:45:09.488          48              5      227.26
998  2024-04-24 09:45:09.488          31              7       59.93
999  2024-04-24 09:45:09.488           3              4      366.26
1000 2023-10-29 09:45:09.488          32              6      334.89
1001 2023-10-29 09:45:09.488          13              3      109.29

[1002 rows x 4 columns]

In [48]:
df5.isnull().sum()

Transaction Date    0
Product ID          0
Quantity Sold       0
Sale Price          8
dtype: int64

In [51]:
df5['Sale Price'] = df5['Sale Price'].fillna(df5['Sale Price'].mean())
df5.head(10)

         Transaction Date  Product ID  Quantity Sold  Sale Price
0 2023-10-28 09:45:09.488          50              4   11.870000
1 2023-10-28 09:45:09.488          35              1  358.020000
2 2023-10-28 09:45:09.488          42              6  254.771169
3 2023-10-28 09:45:09.488          19              5   17.010000
4 2023-10-28 09:45:09.488          46              3  204.310000
5 2023-10-28 09:45:09.488          22              5  254.771169
6 2023-10-28 09:45:09.488           7              4  388.840000
7 2023-10-29 09:45:09.488           4              7   36.770000
8 2023-10-29 09:45:09.488          13              3  109.290000
9 2023-10-29 09:45:09.488          32              6  334.890000

In [16]:
import pandas as pd
df5 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name = 'Sales Data Missing')
df5.head(8)

         Transaction Date  Product ID  Quantity Sold  Sale Price
0 2023-10-28 09:45:09.488          50              4       11.87
1 2023-10-28 09:45:09.488          35              1      358.02
2 2023-10-28 09:45:09.488          42              6         NaN
3 2023-10-28 09:45:09.488          19              5       17.01
4 2023-10-28 09:45:09.488          46              3      204.31
5 2023-10-28 09:45:09.488          22              5         NaN
6 2023-10-28 09:45:09.488           7              4      388.84
7 2023-10-29 09:45:09.488           4              7       36.77

In [17]:
df5 = df5.dropna()
df5.head(8)

         Transaction Date  Product ID  Quantity Sold  Sale Price
0 2023-10-28 09:45:09.488          50              4       11.87
1 2023-10-28 09:45:09.488          35              1      358.02
3 2023-10-28 09:45:09.488          19              5       17.01
4 2023-10-28 09:45:09.488          46              3      204.31
6 2023-10-28 09:45:09.488           7              4      388.84
7 2023-10-29 09:45:09.488           4              7       36.77
8 2023-10-29 09:45:09.488          13              3      109.29
9 2023-10-29 09:45:09.488          32              6      334.89

In [6]:
df5[df5.duplicated()]

            Transaction Date  Product ID  Quantity Sold  Sale Price
1000 2023-10-29 09:45:09.488          32              6      334.89
1001 2023-10-29 09:45:09.488          13              3      109.29

In [9]:
df5['Sale Price'].unique()

array([ 11.87, 358.02,    nan,  17.01, 204.31, 388.84,  36.77, 109.29,
       334.89, 329.59,  61.89, 264.88, 396.6 , 236.24, 298.83, 346.64,
       108.14, 495.75, 237.41, 395.24, 257.92, 132.99, 203.61, 318.48,
       490.56, 429.31, 277.86, 433.14, 242.17,  82.91, 229.36, 480.71,
       442.9 , 299.65, 428.35, 297.92, 183.84, 220.91, 235.58,  74.43,
       187.31,  91.81,  44.12, 371.56, 309.28, 179.22, 471.93, 415.48,
       380.54,  97.89, 406.04, 354.24, 371.97, 221.69, 479.32, 329.62,
        21.56, 144.6 , 158.93, 446.17, 112.5 , 232.46, 425.73, 105.96,
       120.8 , 448.11, 354.11, 120.44, 154.7 , 329.3 ,  15.93, 494.14,
       154.57, 289.07,  64.25, 476.23,  21.44, 399.34, 234.42,  26.99,
       251.97, 412.87,  43.54, 407.33, 481.78,  55.99, 162.5 , 228.32,
       364.49, 118.22, 367.3 , 271.36, 234.68, 354.89, 489.76, 251.24,
        56.75, 475.88, 471.45, 145.64, 360.02, 211.4 , 337.6 , 363.85,
        79.87, 128.57, 455.87, 401.21, 398.37, 459.57, 281.32, 496.99,
       255.31, 314.25, 220.06, 157.62, 342.13, 336.63, 425.54, 258.63,
        22.34, 109.58, 403.94, 132.73, 210.61,  17.54, 386.11, 128.53,
       108.23, 146.59, 496.69,  31.51, 257.67, 341.79, 323.9 , 127.54,
       482.4 , 339.71, 482.86, 144.62, 150.83,  63.54, 325.97, 155.67,
       176.9 , 193.91,  72.65,  35.4 , 128.59,  30.79, 190.22, 416.35,
       192.15, 228.75,  44.76,  14.34, 180.49, 110.61, 429.7 , 148.41,
       497.46, 322.08,  70.27, 216.8 , 445.32,  85.69, 399.31, 373.04,
       137.18, 248.14, 215.28, 432.23,  31.43, 294.43, 342.  , 107.51,
       404.4 , 300.84, 158.43, 395.9 , 198.26, 151.32, 492.58, 407.45,
       300.89, 247.2 , 356.47, 367.14, 447.35, 172.9 , 360.07,  69.07,
       221.18, 387.38,  10.66,  75.58, 381.08, 463.93,  45.44, 280.73,
       346.98, 103.15, 307.3 , 134.65,  19.37,  59.93, 450.29,  10.01,
        66.91, 319.34, 301.61,  33.61,  75.79,  38.34,  24.29,  91.76,
        18.6 , 243.45, 264.33,  53.75, 421.5 , 458.13, 364.75, 100.81,
       359.89, 324.45, 130.94, 371.91, 405.28, 303.53, 126.34, 292.87,
       265.51, 438.37, 394.74, 167.53, 300.68, 314.98, 127.36, 184.94,
       415.09, 370.9 , 332.1 , 417.37, 425.01, 492.17, 159.6 , 147.22,
       142.84,  14.44, 423.39, 263.12,  68.07, 392.38, 439.18, 285.42,
       294.24,  98.99, 343.25, 451.95, 320.71, 372.55, 340.32, 259.36,
        60.23, 469.77,  79.57, 350.13, 326.45, 315.59, 235.24, 321.84,
       447.34,  44.79, 339.62,  10.77, 338.66,  16.74, 107.64, 422.31,
       198.08, 222.04, 383.28,  69.3 , 434.72, 120.75, 144.94, 153.81,
       347.32, 337.22, 316.14, 222.57, 265.44,  74.02, 480.96, 290.3 ,
       424.35,  29.11, 305.44, 453.99, 150.03, 343.01, 433.99, 479.39,
       376.71,  91.99,  70.23, 319.15, 150.02, 378.08, 479.15, 156.79,
        42.56, 108.64, 248.96,  16.08, 199.95, 349.87, 187.34, 497.76,
       263.8 , 415.84, 350.35, 388.1 , 393.77, 489.7 , 481.76,  52.68,
       485.43, 466.56, 204.83, 210.72, 307.8 ,  34.61, 371.58, 173.68,
       275.29, 460.03, 155.31, 265.52, 490.76, 419.55, 292.79, 445.44,
       216.7 , 295.63, 302.86,  34.49, 472.41, 297.07,  89.72, 403.71,
       374.01, 358.89, 315.47, 405.51, 312.36, 209.7 , 306.83, 455.63,
       310.16, 176.79, 296.05, 204.94, 418.09, 182.95, 426.67, 243.65,
       441.28, 490.68, 266.06, 434.39, 307.87, 116.77,  70.94, 490.38,
        35.06, 172.47, 346.43, 304.53, 262.77, 205.53, 222.08, 402.  ,
        39.17, 218.36, 295.28, 150.86, 208.1 , 247.94,  18.3 , 377.96,
       354.81, 229.06, 340.27, 146.15, 483.54, 214.98, 476.59, 243.4 ,
        25.17,  48.05, 202.3 , 392.85, 400.37, 487.36, 319.82, 383.33,
       179.8 , 420.15, 117.34, 240.29, 424.5 , 278.94, 355.39, 412.6 ,
       153.19, 169.39,  47.66,  27.65, 195.76,  47.36, 113.88, 261.79,
        59.31, 165.3 , 472.58, 347.25,  30.59, 339.75, 260.52, 299.93,
        53.42, 274.99, 179.16, 486.81, 252.16, 263.18, 131.2 , 164.66,
       359.39, 485.63, 131.3 , 389.2 , 260.45, 118.82, 379.18, 136.23,
       165.62, 222.67, 482.11,  40.72, 414.73, 140.14, 280.83, 263.55,
       430.21, 314.12, 180.92,  95.86, 482.37, 179.48,  23.49,  17.2 ,
       359.47, 291.03, 122.9 ,  29.08, 438.11, 349.34, 452.2 , 177.8 ,
       467.13, 446.21, 283.73, 327.43, 454.73, 164.97, 258.07, 304.32,
       478.83, 404.49, 159.33, 476.2 , 121.6 , 304.76,  43.81, 223.94,
       149.29, 473.9 , 125.14, 420.86, 209.48, 484.58,  47.04, 351.63,
       243.02, 164.03,  35.65, 359.84,  79.65, 261.21,  64.38, 277.82,
       105.67, 154.69,  44.87, 254.46, 364.13, 119.9 , 356.78,  40.48,
       488.73, 253.17, 190.67, 214.09, 166.24, 292.83, 147.69, 137.54,
        61.07,  14.43, 436.89, 341.33, 374.16, 230.18, 329.06, 427.61,
        95.14, 190.84, 394.04,  82.01, 185.77, 172.36, 270.16, 298.48,
        80.01, 415.95, 103.88, 215.53,  36.62, 385.12, 185.7 , 251.5 ,
       131.7 ,  78.87, 284.62,  62.93, 194.89, 299.41,  43.08,  71.52,
        78.99, 473.76,  65.16,  10.72, 200.11, 151.55, 220.67,  35.32,
        48.69, 112.35, 410.22, 488.63, 305.86, 396.58, 358.74, 140.01,
       163.32, 472.92, 217.09, 483.75, 369.88, 312.22, 436.99, 136.77,
       191.85,  42.19, 413.04, 162.81, 266.03, 205.02, 174.25, 188.65,
       403.27, 305.78, 356.25, 115.71, 156.05, 379.58, 130.84, 243.68,
        26.26,  40.64, 421.11, 470.98, 235.04, 303.5 , 321.62,  33.59,
       486.05, 271.64, 179.14, 353.57, 418.73, 141.58, 209.99, 186.51,
       356.42,  68.9 , 333.9 , 344.48, 457.51, 467.03, 142.99, 134.02,
       472.78, 151.73, 342.55, 439.77, 339.02, 436.28, 483.36,  75.87,
       214.12, 106.09, 341.25, 293.37, 260.11, 184.99, 156.96, 115.06,
       382.91,  14.08, 325.01, 355.23, 410.39, 127.8 , 113.25, 475.76,
       142.7 ,  45.72, 447.23, 440.7 , 465.32, 161.59, 276.68,  47.72,
       111.43, 212.68, 251.84,  85.87, 483.85, 461.29, 283.28, 174.45,
       106.49, 255.3 , 463.84, 191.87, 385.4 , 385.37, 225.18, 217.14,
       346.3 , 203.34, 459.94, 241.42, 323.83, 145.13, 341.64, 269.53,
       123.87, 320.73, 498.93, 490.78, 156.9 , 447.61, 274.16, 382.89,
        91.22, 224.45, 290.16,  87.06,  55.11, 146.85, 475.72,  64.39,
       399.16, 379.44, 430.59, 480.47,  88.41,  80.  ,  45.14,  84.28,
       233.56, 182.99, 454.53, 332.68,  49.29, 230.67, 274.94, 180.57,
       357.57, 373.53, 413.66, 488.25, 178.15, 474.37, 374.36, 110.29,
       121.32, 367.2 , 418.49, 359.18, 496.48, 261.2 , 404.17, 478.46,
       217.05, 387.85, 413.26, 154.36, 316.85, 314.95, 169.3 , 416.4 ,
       180.17, 277.75, 193.53,  22.47, 337.91, 163.84, 256.51,  45.81,
        28.41, 102.38, 460.57, 253.38,  42.34,  74.54, 196.45, 276.08,
       255.2 , 245.64, 441.35, 147.53, 155.65, 200.2 , 198.33, 222.06,
        27.99, 353.56, 398.64,  18.82, 393.09, 392.51, 434.13,  61.63,
       198.41, 264.16, 425.06, 412.99, 239.7 , 167.62, 141.03, 437.65,
        13.84, 258.39, 208.22, 376.84, 349.32, 412.39, 326.76, 209.72,
        49.76,  14.96, 160.32, 222.46, 182.66, 159.06, 275.44,  55.39,
       203.62, 220.96, 290.17,  38.47, 137.35, 362.04,  32.37,  17.4 ,
        40.6 , 107.62, 334.59, 222.95, 196.4 , 227.58, 234.27, 185.33,
        89.89, 111.47, 421.28,  59.67,  48.44, 451.04, 320.03, 200.85,
       295.58, 455.72,  10.07, 475.96, 139.5 , 156.7 , 428.96, 246.87,
       327.77, 367.38, 176.04, 175.3 , 158.44, 192.14,  38.25, 189.18,
       191.76, 241.52, 325.63, 389.92, 152.12, 246.2 , 369.02,  13.76,
        12.7 ,  41.18, 142.42, 388.73, 320.84, 158.14, 276.8 ,  59.88,
       204.54, 137.07, 354.29,  15.59, 384.62, 442.67, 331.75, 257.35,
        71.16, 193.22, 345.87, 190.95, 153.72, 236.71,  57.3 , 321.69,
       163.54,  29.34, 419.39, 148.42, 208.5 ,  32.96,  85.53, 489.48,
       128.55,  71.87,  76.93, 246.69, 114.2 , 478.4 , 105.37, 240.93,
       144.3 , 185.32, 479.21, 224.13, 229.68, 230.62,  82.18,  14.86,
       207.41, 152.35, 397.35, 150.94, 330.05, 199.4 , 202.67, 234.88,
        19.47,  43.49, 249.56, 361.98,  45.17, 422.93, 147.95,  95.69,
       240.87, 303.2 , 314.43, 372.83, 261.06, 396.34, 161.8 , 366.07,
       316.19,  78.61, 141.12, 439.96, 478.01,  37.73, 428.44, 477.98,
       474.07, 336.53,  66.32,  64.64, 330.78,  89.22, 186.42, 160.09,
       286.4 , 145.32,  32.01, 310.51, 369.04, 452.42, 121.84, 335.84,
       446.15, 389.26, 381.91, 317.03, 386.77, 433.64, 225.82,  97.84,
       145.4 , 191.21, 286.89, 376.25, 459.15, 453.98, 294.99, 288.99,
       248.94,  65.52, 132.94, 429.29, 307.47, 379.59, 322.47,  47.05,
       310.67, 405.46, 456.28, 101.21, 142.49, 331.81, 308.9 ,  78.21,
       172.77, 488.88, 222.86,  15.96, 381.8 ,  65.78,  15.74, 376.92,
       447.02,  66.1 , 459.86, 355.74, 339.51, 305.71, 253.79, 432.69,
       405.41, 454.87, 227.26, 366.26])